-- Base architecture schema for Estimating / Bid / Catalog / Documents / Drawings / Takeoff / Estimate / Proposal.
-- MySQL 8+, InnoDB, utf8mb4.
-- Intentionally excludes identity and access-control tables.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS estimators (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    display_name VARCHAR(191) NOT NULL,
    email VARCHAR(191) NULL,
    phone VARCHAR(100) NULL,
    company_name VARCHAR(191) NULL,
    trade VARCHAR(100) NULL,
    metadata_json JSON NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_estimators_email (email),
    KEY idx_estimators_active_deleted (active, deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_templates (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(191) NOT NULL,
    description TEXT NULL,
    trade VARCHAR(100) NULL,
    settings_json JSON NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_project_templates_active_deleted (active, deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_template_id BIGINT UNSIGNED NULL,
    estimator_id BIGINT UNSIGNED NULL,
    project_number VARCHAR(100) NULL,
    name VARCHAR(191) NOT NULL,
    description TEXT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'draft',
    client_name VARCHAR(191) NULL,
    job_address VARCHAR(255) NULL,
    city VARCHAR(100) NULL,
    state VARCHAR(100) NULL,
    postal_code VARCHAR(30) NULL,
    country VARCHAR(100) NULL,
    bid_due_at DATETIME NULL,
    start_date DATE NULL,
    end_date DATE NULL,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_projects_project_number (project_number),
    KEY idx_projects_template (project_template_id),
    KEY idx_projects_estimator (estimator_id),
    KEY idx_projects_status_deleted (status, deleted_at),
    KEY idx_projects_bid_due (bid_due_at),
    CONSTRAINT fk_projects_template FOREIGN KEY (project_template_id) REFERENCES project_templates(id) ON DELETE SET NULL,
    CONSTRAINT fk_projects_estimator FOREIGN KEY (estimator_id) REFERENCES estimators(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS estimating (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NOT NULL,
    estimator_id BIGINT UNSIGNED NULL,
    name VARCHAR(191) NOT NULL,
    description TEXT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'draft',
    currency_code CHAR(3) NOT NULL DEFAULT 'USD',
    settings_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_estimating_project (project_id),
    KEY idx_estimating_estimator (estimator_id),
    KEY idx_estimating_status_deleted (status, deleted_at),
    CONSTRAINT fk_estimating_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_estimating_estimator FOREIGN KEY (estimator_id) REFERENCES estimators(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bid_statuses (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_terminal TINYINT(1) NOT NULL DEFAULT 0,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_bid_statuses_code (code),
    KEY idx_bid_statuses_sort (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bids (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NULL,
    estimating_id BIGINT UNSIGNED NULL,
    bid_status_id BIGINT UNSIGNED NULL,
    estimator_id BIGINT UNSIGNED NULL,
    bid_number VARCHAR(100) NULL,
    name VARCHAR(191) NOT NULL,
    requester_company VARCHAR(191) NULL,
    project_name_snapshot VARCHAR(191) NULL,
    due_at DATETIME NULL,
    submitted_at DATETIME NULL,
    awarded_at DATETIME NULL,
    total_amount DECIMAL(18,4) NOT NULL DEFAULT 0,
    currency_code CHAR(3) NOT NULL DEFAULT 'USD',
    notes TEXT NULL,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_bids_bid_number (bid_number),
    KEY idx_bids_project (project_id),
    KEY idx_bids_estimating (estimating_id),
    KEY idx_bids_status (bid_status_id),
    KEY idx_bids_estimator (estimator_id),
    KEY idx_bids_due (due_at),
    CONSTRAINT fk_bids_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL,
    CONSTRAINT fk_bids_estimating FOREIGN KEY (estimating_id) REFERENCES estimating(id) ON DELETE SET NULL,
    CONSTRAINT fk_bids_status FOREIGN KEY (bid_status_id) REFERENCES bid_statuses(id) ON DELETE SET NULL,
    CONSTRAINT fk_bids_estimator FOREIGN KEY (estimator_id) REFERENCES estimators(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS catalogs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(191) NOT NULL,
    description TEXT NULL,
    trade VARCHAR(100) NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    locked TINYINT(1) NOT NULL DEFAULT 0,
    enabled_for_projects TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_catalogs_active_deleted (active, deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cost_catalogs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    catalog_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(191) NOT NULL,
    description TEXT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'USD',
    effective_from DATE NULL,
    effective_to DATE NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_cost_catalogs_catalog (catalog_id),
    KEY idx_cost_catalogs_effective (effective_from, effective_to),
    CONSTRAINT fk_cost_catalogs_catalog FOREIGN KEY (catalog_id) REFERENCES catalogs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS catalog_groups (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    catalog_id BIGINT UNSIGNED NOT NULL,
    parent_group_id BIGINT UNSIGNED NULL,
    name VARCHAR(191) NOT NULL,
    description TEXT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    active TINYINT(1) NOT NULL DEFAULT 1,
    enabled_for_projects TINYINT(1) NOT NULL DEFAULT 1,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_catalog_groups_catalog (catalog_id),
    KEY idx_catalog_groups_parent (parent_group_id),
    CONSTRAINT fk_catalog_groups_catalog FOREIGN KEY (catalog_id) REFERENCES catalogs(id) ON DELETE CASCADE,
    CONSTRAINT fk_catalog_groups_parent FOREIGN KEY (parent_group_id) REFERENCES catalog_groups(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS catalog_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    catalog_id BIGINT UNSIGNED NOT NULL,
    cost_catalog_id BIGINT UNSIGNED NULL,
    catalog_group_id BIGINT UNSIGNED NULL,
    sku VARCHAR(100) NULL,
    name VARCHAR(191) NOT NULL,
    description TEXT NULL,
    item_type ENUM('part','material','assembly','labor','equipment','subcontractor','travel','custom') NOT NULL DEFAULT 'material',
    cost_type VARCHAR(100) NULL,
    unit_of_measure VARCHAR(50) NOT NULL DEFAULT 'ea',
    measurement_type VARCHAR(32) NOT NULL DEFAULT 'count',
    unit_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    material_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    labor_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    equipment_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    subcontractor_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    labor_hours DECIMAL(18,4) NOT NULL DEFAULT 0,
    labor_rate DECIMAL(18,4) NOT NULL DEFAULT 0,
    markup_percent DECIMAL(9,4) NOT NULL DEFAULT 0,
    waste_factor_percent DECIMAL(9,4) NOT NULL DEFAULT 0,
    size VARCHAR(100) NULL,
    diameter VARCHAR(100) NULL,
    trade_size VARCHAR(100) NULL,
    thickness VARCHAR(100) NULL,
    gauge VARCHAR(100) NULL,
    material VARCHAR(100) NULL,
    color VARCHAR(50) NULL,
    symbol VARCHAR(50) NULL,
    marker_size DECIMAL(9,4) NULL,
    taxable TINYINT(1) NOT NULL DEFAULT 1,
    manufacturer VARCHAR(191) NULL,
    supplier VARCHAR(191) NULL,
    catalog_number VARCHAR(100) NULL,
    sub_job_code VARCHAR(100) NULL,
    sub_job_name VARCHAR(191) NULL,
    epd_url VARCHAR(1024) NULL,
    cost_code VARCHAR(100) NULL,
    masterformat VARCHAR(100) NULL,
    uniformat VARCHAR(100) NULL,
    attachment_url VARCHAR(1024) NULL,
    tags_json JSON NULL,
    attributes_json JSON NULL,
    notes TEXT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_catalog_items_catalog (catalog_id),
    KEY idx_catalog_items_cost_catalog (cost_catalog_id),
    KEY idx_catalog_items_group (catalog_group_id),
    KEY idx_catalog_items_sku (sku),
    KEY idx_catalog_items_type (item_type),
    KEY idx_catalog_items_active_deleted (active, deleted_at),
    CONSTRAINT fk_catalog_items_catalog FOREIGN KEY (catalog_id) REFERENCES catalogs(id) ON DELETE CASCADE,
    CONSTRAINT fk_catalog_items_cost_catalog FOREIGN KEY (cost_catalog_id) REFERENCES cost_catalogs(id) ON DELETE SET NULL,
    CONSTRAINT fk_catalog_items_group FOREIGN KEY (catalog_group_id) REFERENCES catalog_groups(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS catalog_item_attributes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    catalog_item_id BIGINT UNSIGNED NOT NULL,
    attribute_name VARCHAR(100) NOT NULL,
    attribute_value TEXT NULL,
    value_type VARCHAR(50) NOT NULL DEFAULT 'string',
    unit_of_measure VARCHAR(50) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_catalog_item_attributes_item (catalog_item_id),
    KEY idx_catalog_item_attributes_name (attribute_name),
    CONSTRAINT fk_catalog_item_attributes_item FOREIGN KEY (catalog_item_id) REFERENCES catalog_items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS assembly_parts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    assembly_catalog_item_id BIGINT UNSIGNED NOT NULL,
    part_catalog_item_id BIGINT UNSIGNED NOT NULL,
    quantity DECIMAL(18,6) NOT NULL DEFAULT 1,
    unit_cost_snapshot DECIMAL(18,4) NOT NULL DEFAULT 0,
    unit_labor_time_snapshot DECIMAL(18,4) NOT NULL DEFAULT 0,
    ratio_type ENUM('fixed','per_unit','per_linear_length','per_area','per_endpoint','spacing_based') NOT NULL DEFAULT 'per_unit',
    spacing_value DECIMAL(18,6) NULL,
    waste_factor_percent DECIMAL(9,4) NOT NULL DEFAULT 0,
    notes TEXT NULL,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_assembly_parts_assembly (assembly_catalog_item_id),
    KEY idx_assembly_parts_part (part_catalog_item_id),
    CONSTRAINT fk_assembly_parts_assembly FOREIGN KEY (assembly_catalog_item_id) REFERENCES catalog_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_assembly_parts_part FOREIGN KEY (part_catalog_item_id) REFERENCES catalog_items(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS document_folders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NOT NULL,
    parent_folder_id BIGINT UNSIGNED NULL,
    name VARCHAR(191) NOT NULL,
    description TEXT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_document_folders_project (project_id),
    KEY idx_document_folders_parent (parent_folder_id),
    CONSTRAINT fk_document_folders_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_document_folders_parent FOREIGN KEY (parent_folder_id) REFERENCES document_folders(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_documents (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NOT NULL,
    document_folder_id BIGINT UNSIGNED NULL,
    document_type VARCHAR(100) NOT NULL DEFAULT 'document',
    title VARCHAR(191) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    storage_path VARCHAR(1024) NOT NULL,
    mime_type VARCHAR(191) NULL,
    file_size BIGINT UNSIGNED NULL,
    version_number INT UNSIGNED NOT NULL DEFAULT 1,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_project_documents_project (project_id),
    KEY idx_project_documents_folder (document_folder_id),
    KEY idx_project_documents_type (document_type),
    CONSTRAINT fk_project_documents_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_project_documents_folder FOREIGN KEY (document_folder_id) REFERENCES document_folders(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS drawings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NOT NULL,
    project_document_id BIGINT UNSIGNED NULL,
    drawing_number VARCHAR(100) NULL,
    title VARCHAR(191) NOT NULL,
    discipline VARCHAR(100) NULL,
    sheet_number VARCHAR(100) NULL,
    revision VARCHAR(100) NULL,
    page_count INT UNSIGNED NOT NULL DEFAULT 1,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_drawings_project (project_id),
    KEY idx_drawings_document (project_document_id),
    KEY idx_drawings_number (drawing_number),
    CONSTRAINT fk_drawings_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_drawings_document FOREIGN KEY (project_document_id) REFERENCES project_documents(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS drawing_scales (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    drawing_id BIGINT UNSIGNED NOT NULL,
    page_number INT UNSIGNED NOT NULL DEFAULT 1,
    scale_name VARCHAR(100) NOT NULL,
    ratio DECIMAL(18,8) NOT NULL,
    unit VARCHAR(50) NOT NULL DEFAULT 'ft',
    pixels_per_unit DECIMAL(18,8) NULL,
    calibration_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_drawing_scales_drawing_page (drawing_id, page_number),
    CONSTRAINT fk_drawing_scales_drawing FOREIGN KEY (drawing_id) REFERENCES drawings(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS takeoffs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NOT NULL,
    drawing_id BIGINT UNSIGNED NULL,
    estimate_id BIGINT UNSIGNED NULL,
    name VARCHAR(191) NOT NULL,
    description TEXT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'draft',
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_takeoffs_project (project_id),
    KEY idx_takeoffs_drawing (drawing_id),
    KEY idx_takeoffs_estimate (estimate_id),
    KEY idx_takeoffs_status_deleted (status, deleted_at),
    CONSTRAINT fk_takeoffs_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_takeoffs_drawing FOREIGN KEY (drawing_id) REFERENCES drawings(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS takeoff_layers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    takeoff_id BIGINT UNSIGNED NOT NULL,
    drawing_id BIGINT UNSIGNED NULL,
    page_number INT UNSIGNED NOT NULL DEFAULT 1,
    project_id BIGINT UNSIGNED NULL,
    group_name VARCHAR(191) NULL,
    name VARCHAR(191) NOT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'mixed',
    layer_type ENUM('count','linear','area','volume','mixed') NOT NULL DEFAULT 'mixed',
    takeoff_type VARCHAR(50) NOT NULL DEFAULT 'count',
    unit_of_measure VARCHAR(50) NOT NULL DEFAULT 'ea',
    catalog_item_id BIGINT UNSIGNED NULL,
    assembly_id BIGINT UNSIGNED NULL,
    assembly_catalog_item_id BIGINT UNSIGNED NULL,
    color VARCHAR(50) NOT NULL DEFAULT '#2563eb',
    symbol VARCHAR(50) NOT NULL DEFAULT 'circle',
    tag VARCHAR(100) NULL,
    symbol_size VARCHAR(50) NULL,
    quantity DECIMAL(18,6) NOT NULL DEFAULT 0,
    visible TINYINT(1) NOT NULL DEFAULT 1,
    locked TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_takeoff_layers_takeoff (takeoff_id),
    KEY idx_takeoff_layers_drawing_page (drawing_id, page_number),
    KEY idx_takeoff_layers_catalog_item (catalog_item_id),
    KEY idx_takeoff_layers_assembly (assembly_catalog_item_id),
    CONSTRAINT fk_takeoff_layers_takeoff FOREIGN KEY (takeoff_id) REFERENCES takeoffs(id) ON DELETE CASCADE,
    CONSTRAINT fk_takeoff_layers_drawing FOREIGN KEY (drawing_id) REFERENCES drawings(id) ON DELETE SET NULL,
    CONSTRAINT fk_takeoff_layers_catalog_item FOREIGN KEY (catalog_item_id) REFERENCES catalog_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_takeoff_layers_assembly FOREIGN KEY (assembly_catalog_item_id) REFERENCES catalog_items(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS takeoff_measurements (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    takeoff_id BIGINT UNSIGNED NOT NULL,
    takeoff_layer_id BIGINT UNSIGNED NOT NULL,
    drawing_id BIGINT UNSIGNED NULL,
    drawing_scale_id BIGINT UNSIGNED NULL,
    page_number INT UNSIGNED NOT NULL DEFAULT 1,
    measurement_type ENUM('count','linear','area','volume') NOT NULL,
    catalog_item_id BIGINT UNSIGNED NULL,
    assembly_catalog_item_id BIGINT UNSIGNED NULL,
    geometry_json JSON NOT NULL,
    quantity DECIMAL(18,6) NOT NULL DEFAULT 0,
    measured_value DECIMAL(18,6) NOT NULL DEFAULT 0,
    multiplier DECIMAL(18,6) NOT NULL DEFAULT 1,
    unit_of_measure VARCHAR(50) NOT NULL DEFAULT 'ea',
    label VARCHAR(191) NULL,
    notes TEXT NULL,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_takeoff_measurements_takeoff (takeoff_id),
    KEY idx_takeoff_measurements_layer (takeoff_layer_id),
    KEY idx_takeoff_measurements_drawing_page (drawing_id, page_number),
    KEY idx_takeoff_measurements_item (catalog_item_id),
    CONSTRAINT fk_takeoff_measurements_takeoff FOREIGN KEY (takeoff_id) REFERENCES takeoffs(id) ON DELETE CASCADE,
    CONSTRAINT fk_takeoff_measurements_layer FOREIGN KEY (takeoff_layer_id) REFERENCES takeoff_layers(id) ON DELETE CASCADE,
    CONSTRAINT fk_takeoff_measurements_drawing FOREIGN KEY (drawing_id) REFERENCES drawings(id) ON DELETE SET NULL,
    CONSTRAINT fk_takeoff_measurements_scale FOREIGN KEY (drawing_scale_id) REFERENCES drawing_scales(id) ON DELETE SET NULL,
    CONSTRAINT fk_takeoff_measurements_item FOREIGN KEY (catalog_item_id) REFERENCES catalog_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_takeoff_measurements_assembly FOREIGN KEY (assembly_catalog_item_id) REFERENCES catalog_items(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS takeoff_tags (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NULL,
    name VARCHAR(100) NOT NULL,
    color VARCHAR(50) NOT NULL DEFAULT '#64748b',
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_takeoff_tags_project (project_id),
    UNIQUE KEY uq_takeoff_tags_project_name (project_id, name),
    CONSTRAINT fk_takeoff_tags_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS takeoff_measurement_tags (
    takeoff_measurement_id BIGINT UNSIGNED NOT NULL,
    takeoff_tag_id BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (takeoff_measurement_id, takeoff_tag_id),
    KEY idx_takeoff_measurement_tags_tag (takeoff_tag_id),
    CONSTRAINT fk_takeoff_measurement_tags_measurement FOREIGN KEY (takeoff_measurement_id) REFERENCES takeoff_measurements(id) ON DELETE CASCADE,
    CONSTRAINT fk_takeoff_measurement_tags_tag FOREIGN KEY (takeoff_tag_id) REFERENCES takeoff_tags(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS estimates (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NOT NULL,
    estimating_id BIGINT UNSIGNED NULL,
    takeoff_id BIGINT UNSIGNED NULL,
    bid_id BIGINT UNSIGNED NULL,
    estimate_number VARCHAR(100) NULL,
    name VARCHAR(191) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'draft',
    currency_code CHAR(3) NOT NULL DEFAULT 'USD',
    subtotal_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    markup_total DECIMAL(18,4) NOT NULL DEFAULT 0,
    tax_total DECIMAL(18,4) NOT NULL DEFAULT 0,
    total_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    labor_hours_total DECIMAL(18,4) NOT NULL DEFAULT 0,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_estimates_number (estimate_number),
    KEY idx_estimates_project (project_id),
    KEY idx_estimates_estimating (estimating_id),
    KEY idx_estimates_takeoff (takeoff_id),
    KEY idx_estimates_bid (bid_id),
    KEY idx_estimates_status_deleted (status, deleted_at),
    CONSTRAINT fk_estimates_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_estimates_estimating FOREIGN KEY (estimating_id) REFERENCES estimating(id) ON DELETE SET NULL,
    CONSTRAINT fk_estimates_takeoff FOREIGN KEY (takeoff_id) REFERENCES takeoffs(id) ON DELETE SET NULL,
    CONSTRAINT fk_estimates_bid FOREIGN KEY (bid_id) REFERENCES bids(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS estimate_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    estimate_id BIGINT UNSIGNED NOT NULL,
    parent_estimate_item_id BIGINT UNSIGNED NULL,
    takeoff_measurement_id BIGINT UNSIGNED NULL,
    takeoff_layer_id BIGINT UNSIGNED NULL,
    catalog_item_id BIGINT UNSIGNED NULL,
    assembly_catalog_item_id BIGINT UNSIGNED NULL,
    source_type VARCHAR(50) NOT NULL DEFAULT 'manual',
    is_manual TINYINT(1) NOT NULL DEFAULT 1,
    is_quantity_locked_from_takeoff TINYINT(1) NOT NULL DEFAULT 0,
    item_type VARCHAR(50) NOT NULL DEFAULT 'line_item',
    group_name VARCHAR(191) NULL,
    budget_code VARCHAR(100) NULL,
    cost_type VARCHAR(100) NULL,
    name VARCHAR(191) NOT NULL,
    description TEXT NULL,
    quantity DECIMAL(18,6) NOT NULL DEFAULT 0,
    unit_of_measure VARCHAR(50) NOT NULL DEFAULT 'ea',
    unit_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    unit_labor_time DECIMAL(18,4) NOT NULL DEFAULT 0,
    material_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    labor_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    equipment_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    subcontractor_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    labor_hours DECIMAL(18,4) NOT NULL DEFAULT 0,
    waste_percentage DECIMAL(9,4) NOT NULL DEFAULT 0,
    margin_percentage DECIMAL(9,4) NOT NULL DEFAULT 0,
    taxable TINYINT(1) NOT NULL DEFAULT 1,
    waste_factor_percent DECIMAL(9,4) NOT NULL DEFAULT 0,
    markup_percent DECIMAL(9,4) NOT NULL DEFAULT 0,
    subtotal_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    total_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_estimate_items_estimate (estimate_id),
    KEY idx_estimate_items_parent (parent_estimate_item_id),
    KEY idx_estimate_items_measurement (takeoff_measurement_id),
    KEY idx_estimate_items_takeoff_layer (takeoff_layer_id),
    KEY idx_estimate_items_catalog_item (catalog_item_id),
    CONSTRAINT fk_estimate_items_estimate FOREIGN KEY (estimate_id) REFERENCES estimates(id) ON DELETE CASCADE,
    CONSTRAINT fk_estimate_items_parent FOREIGN KEY (parent_estimate_item_id) REFERENCES estimate_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_estimate_items_measurement FOREIGN KEY (takeoff_measurement_id) REFERENCES takeoff_measurements(id) ON DELETE SET NULL,
    CONSTRAINT fk_estimate_items_takeoff_layer FOREIGN KEY (takeoff_layer_id) REFERENCES takeoff_layers(id) ON DELETE SET NULL,
    CONSTRAINT fk_estimate_items_catalog_item FOREIGN KEY (catalog_item_id) REFERENCES catalog_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_estimate_items_assembly FOREIGN KEY (assembly_catalog_item_id) REFERENCES catalog_items(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS estimate_markups (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    estimate_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(191) NOT NULL,
    markup_type ENUM('percentage','fixed','tax','discount') NOT NULL DEFAULT 'percentage',
    basis ENUM('subtotal','material','labor','equipment','subcontractor','total') NOT NULL DEFAULT 'subtotal',
    value DECIMAL(18,6) NOT NULL DEFAULT 0,
    amount DECIMAL(18,4) NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_estimate_markups_estimate (estimate_id),
    CONSTRAINT fk_estimate_markups_estimate FOREIGN KEY (estimate_id) REFERENCES estimates(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS proposals (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NOT NULL,
    estimate_id BIGINT UNSIGNED NULL,
    bid_id BIGINT UNSIGNED NULL,
    proposal_number VARCHAR(100) NULL,
    title VARCHAR(191) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'draft',
    valid_until DATE NULL,
    subtotal DECIMAL(18,4) NOT NULL DEFAULT 0,
    total DECIMAL(18,4) NOT NULL DEFAULT 0,
    currency_code CHAR(3) NOT NULL DEFAULT 'USD',
    terms TEXT NULL,
    scope TEXT NULL,
    exclusions TEXT NULL,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_proposals_number (proposal_number),
    KEY idx_proposals_project (project_id),
    KEY idx_proposals_estimate (estimate_id),
    KEY idx_proposals_bid (bid_id),
    KEY idx_proposals_status_deleted (status, deleted_at),
    CONSTRAINT fk_proposals_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_proposals_estimate FOREIGN KEY (estimate_id) REFERENCES estimates(id) ON DELETE SET NULL,
    CONSTRAINT fk_proposals_bid FOREIGN KEY (bid_id) REFERENCES bids(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS company_settings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    setting_key VARCHAR(100) NOT NULL,
    setting_value TEXT NULL,
    value_type VARCHAR(50) NOT NULL DEFAULT 'string',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_company_settings_key (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS company_cost_types (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS company_project_statuses (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS company_estimate_types (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS company_setting_users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    display_name VARCHAR(191) NOT NULL,
    email VARCHAR(191) NULL,
    role_name VARCHAR(100) NOT NULL DEFAULT 'Estimator',
    status VARCHAR(50) NOT NULL DEFAULT 'Active',
    estimator_flag TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO bid_statuses (code, name, sort_order, is_terminal) VALUES
    ('invitations', 'Invitations', 10, 0),
    ('to_do', 'To Do', 20, 0),
    ('estimating', 'Estimating', 30, 0),
    ('bid_submitted', 'Bid Submitted', 40, 0),
    ('accepted', 'Accepted', 50, 0),
    ('in_progress', 'In Progress', 60, 0),
    ('complete', 'Complete', 70, 1),
    ('estimadores', 'Estimadores', 80, 0),
    ('lost', 'Lost', 90, 1),
    ('archived', 'Archived', 100, 1)
ON DUPLICATE KEY UPDATE name = VALUES(name), sort_order = VALUES(sort_order), is_terminal = VALUES(is_terminal);

SET FOREIGN_KEY_CHECKS = 1;
